stages:
  - test

test:
  image: python:3.8
  stage: test
  tags:
    - kube-dev
  script:
    - pip install -e .
    - pip install pytest pytest-asyncio coverage
    - MONGODB_URL=mongodb://localhost:27017 coverage run --source=src/ -m pytest
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

