include:
  - project: 'Web-Projects/pipeline-scripts'
    ref: master
    file: '/templates/security.yml'

variables:
  SEC_CS_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  SEC_CS_DOCKERFILE_PATH: Dockerfile
  DEFECTDOJO_PRODUCT_TYPE: "CDB"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master" && $BUILT_AS_BRIDGE == null
      when: never
    - if: $CI_COMMIT_BRANCH && $BUILT_AS_BRIDGE
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
    - when: never

stages:
  - build
  - test
  - security

build:
  stage: build
  image: docker:18.09.9-git
  tags:
    - docker
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

check:
  image: python:3.8
  stage: test
  tags:
    - kube-dev
  before_script:
    - pip install --upgrade pip
    - pip install uv
    - uv sync --frozen --no-cache
  script:
    - uv run --active ruff check
    - uv run --active ruff format --check
    - uv run mypy src tests
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  image: python:3.8
  stage: test
  tags:
    - kube-dev
  before_script:
    - pip install --upgrade pip
    - pip install uv
    - uv sync --frozen --no-cache
  script:
    - uv run coverage run --source=src/ -m pytest
    - uv run coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
