stages:
  - test

test:
  image: python:3.8
  stage: test
  tags:
    - kube-dev
  before_script:
    - pip install --upgrade pip
    - pip install uv
    - uv sync --frozen --no-cache
  script:
    - uv run coverage run --source=src/ -m pytest
    - uv run coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
